# Generated by Django 2.2 on 2019-04-07 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.TextField(max_length=500)),
                ('raca', models.CharField(max_length=30)),
                ('cor_pelos', models.CharField(max_length=30)),
                ('cor_olhos', models.CharField(max_length=30)),
                ('tipo_pelagem', models.CharField(max_length=30)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('data_resgate', models.DateField()),
                ('adotado', models.BooleanField(default=False)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_animais')),
            ],
        ),
    ]
