# Generated by Django 2.2 on 2019-04-07 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doghouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='tipo_animal',
            field=models.CharField(choices=[('C', 'Cachorro'), ('G', 'Gato')], default='C', max_length=1),
        ),
    ]
