# Generated by Django 2.2 on 2019-04-08 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doghouse', '0003_auto_20190408_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='adotado',
            field=models.BooleanField(choices=[('False', 'false'), ('True', 'true')], default=False),
        ),
    ]
